### PR TITLE
this will help people understand that it need to be a list

### PR DESCRIPTION
**Pull request by orena1**

### CODE REVIEW

**Comment by nschloe** [comment]
It'd be lovely if this worked, however: 
> Don't use a empty list as default argument in Python.

https://docs.python.org/3/reference/compound_stmts.html#function-definitions

https://stackoverflow.com/questions/366422/what-is-the-pythonic-way-to-avoid-default-parameters-that-are-empty-lists

**Comment by orena1** [comment]
Thank for the info ,so I assume a function definition is needed. Anyway, thanks for the package, it is great for monitoring cluster queue!

**Comment by zzz4zzz** [comment]
If you don't care about python2 you can just declare typing:
```python
def plot(
    x,
    y,
    width: int=80,
    height: int=25,
    label: Optional[str]=None,
    xlim: Optional[Tuple[float, float]]=None,
    ylim: Optional[Tuple[float, float]]=None,
    xlabel: Optional[str]=None,
    title: Optional[str]=None,
    extra_gnuplot_arguments: Optional[List[str]]=None,
    plot_command: str="plot '-' w lines",
    ticks_scale: float=0,
):
```

**Comment by orena1** [comment]
Looks good, anyway pip2 is not supported:
pip3 install -U termplotlib

**Pull request closed without merging**
